openapi: 3.0.0
info:
  title: Chat Message API
  version: 1.0.0
paths: {}
components:
  schemas:
    ChatMessage:
      type: object
      properties:
        type:
          type: string
          enum: [answer, prompt, system-prompt, directive, tool]
          default: answer
        header:
          type: object
          properties:
            icon:
              $ref: '#/components/schemas/IconType'
            status:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/Status'
                icon:
                  $ref: '#/components/schemas/IconType'
                text:
                  type: string
          allOf:
            - $ref: '#/components/schemas/ChatMessageWithoutHeader'
        buttons:
          type: array
          items:
            $ref: '#/components/schemas/Button'
        body:
          type: string
        messageId:
          type: string
        canBeVoted:
          type: boolean
        relatedContent:
          type: object
          properties:
            title:
              type: string
            content:
              type: array
              items:
                $ref: '#/components/schemas/SourceLink'
        summary:
          type: object
          properties:
            content:
              $ref: '#/components/schemas/ChatMessage'
            collapsedContent:
              type: array
              items:
                $ref: '#/components/schemas/ChatMessage'
        followUp:
          type: object
          properties:
            text:
              type: string
            options:
              type: array
              items:
                $ref: '#/components/schemas/ChatItemAction'
        codeReference:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceTrackerInformation'
        fileList:
          $ref: '#/components/schemas/FileList'
        contextList:
          $ref: '#/components/schemas/FileList'
    # Add placeholder schemas for referenced types
    IconType:
      type: string
      enum: [info, warning, error]
    Status:
      type: string
      enum: [success, warning, error]
    Button:
      type: object
      properties:
        text:
          type: string
        action:
          type: string
    ChatMessageWithoutHeader:
      type: object
      properties:
        text:
          type: string
    SourceLink:
      type: object
      properties:
        url:
          type: string
        title:
          type: string
    ChatItemAction:
      type: object
      properties:
        text:
          type: string
        value:
          type: string
    ReferenceTrackerInformation:
      type: object
      properties:
        file:
          type: string
        line:
          type: integer
    FileList:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          path:
            type: string